name: pacific_dating_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Fonts nzuri (Poppins) kupitia Google Fonts
  google_fonts: ^6.2.1

  # Kuhifadhi lugha iliyochaguliwa (EN/SW) ndani ya device
  shared_preferences: ^2.3.2

  # Supabase
  supabase_flutter: ^2.8.3

  # Media & permissions
  image_picker: ^1.1.2
  record: ^5.2.0
  audioplayers: ^6.0.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1

  # Location
  geolocator: ^13.0.2

dependency_overrides:
  record_linux: ^2.1.1
  record_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Kifurushi cha kutengeneza App Icon moja kwa moja
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

# Usanidi wa App Icon (Weka picha yako kwenye assets/images/app_icon.png)
flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21
